version: "3.7"

services:
  chat-serve:
    container_name: chat-serve
    image: chat-serve
    environment:
      - DATABASE=db
      - USERNAME=user
      - PASSWORD=password
      - HOST=locashot
      - PORT=3306
    networks:
      - proxy

networks:
  proxy:
    external: true
